Repository rapidsai/cugraph-gnn, pull requests merged in 2024-11, with the labels that each got.

#62 add notebook tests, build.sh args
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .gitignore
  build.sh
  ci/build_cpp.sh
  ci/build_python.sh
  ci/test_notebooks.sh
  ci/test_python.sh
  ci/utils/nbtest.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-dgl/meta.yaml
  conda/recipes/cugraph-pyg/meta.yaml
  datasets/get_test_data.sh
  dependencies.yaml
  python/cugraph-dgl/examples/dataset_from_disk_cudf.ipynb
Labels: improvement, non-breaking

#66 start publishing packages
  .github/workflows/build.yaml
Labels: improvement, non-breaking

#67 enforce wheel size limits, README formatting in CI
  ci/build_wheel_cugraph-dgl.sh
  ci/build_wheel_cugraph-pyg.sh
  ci/build_wheel_pylibwholegraph.sh
  ci/validate_wheel.sh
  python/cugraph-dgl/pyproject.toml
  python/cugraph-pyg/README.md
  python/cugraph-pyg/pyproject.toml
  python/pylibwholegraph/README.md
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking

#69 remove versioning workaround for nightlies
  ci/build_cpp.sh
  ci/build_python.sh
  ci/release/update-version.sh
  ci/test_notebooks.sh
  ci/test_python.sh
Labels: improvement, non-breaking

#68 fix devcontainer builds
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#75 Relax PyTorch upper bound (allowing 2.4)
  ci/test_python.sh
  ci/test_wheel_cugraph-dgl.sh
  ci/test_wheel_pylibwholegraph.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-dgl/meta.yaml
  conda/recipes/cugraph-pyg/meta.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
  python/cugraph-dgl/pyproject.toml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/pyproject.toml
Labels: improvement, non-breaking

#74 [Feature] Add gather/scatter support 1D tensor
  python/pylibwholegraph/pylibwholegraph/tests/wholegraph_torch/ops/test_wholegraph_gather_scatter.py
  python/pylibwholegraph/pylibwholegraph/torch/tensor.py
  python/pylibwholegraph/pylibwholegraph/torch/wholememory_ops.py
Labels: feature request, non-breaking

#72 [Bugfix] Dynamic load NVML symbols for better compatibility
  cpp/src/nvml_wrap.cpp
  cpp/src/nvml_wrap.h
  cpp/src/wholememory/communicator.cpp
  cpp/src/wholememory/system_info.cpp
  cpp/src/wholememory/system_info.hpp
Labels: bug, non-breaking

#64 Add breaking change workflow trigger
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#80 Require approval to run CI on draft PRs
  .github/copy-pr-bot.yaml
Labels: improvement, non-breaking
