Repository rapidsai/cugraph-gnn, pull requests merged in 2024-12, with the labels that each got.

#73 [Bugfix] Add stream synchronization before the scatter operation
  cpp/src/wholememory_ops/scatter_op_impl_mapped.cu
Labels: bug, non-breaking

#70 skip conda-python-tests on arm64
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#79 add devcontainers
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/cuda11.8-conda/devcontainer.json
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.5-conda/devcontainer.json
  .devcontainer/cuda12.5-pip/devcontainer.json
  .github/workflows/pr.yaml
  ci/release/update-version.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#89 Disable RockyLinux Tests for DGL, Disable CUDA All 11.4 Tests
  .github/workflows/test.yaml
Labels: breaking, bug

#95 merge branch-24.12 into branch-25.02
  .github/workflows/test.yaml
  CHANGELOG.md
Labels: improvement, non-breaking

#93 Update version references in workflow
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#96 build libwholegraph docs in CI
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  ci/build_docs.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  dependencies.yaml
Labels: doc, non-breaking

#97 fix nightly docs workflow dependencies
  .github/workflows/build.yaml
Labels: improvement, non-breaking
