Repository rapidsai/cugraph-gnn, pull requests merged in 2025-03, with the labels that each got.

#151 Deprecate Unbuffered Sampling in cuGraph-PyG
  python/cugraph-pyg/cugraph_pyg/examples/cugraph_dist_sampling_mg.py
  python/cugraph-pyg/cugraph_pyg/examples/cugraph_dist_sampling_sg.py
  python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py
Labels: breaking, improvement

#153 Drop PyTorch Constraint for OGB
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/test_notebooks.sh
  ci/test_python.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
  python/cugraph-dgl/pyproject.toml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_snmg.py
  python/cugraph-pyg/pyproject.toml
Labels: bug, non-breaking

#143 Add build_type input to `test.yaml`
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#157 Fix update version
  ci/release/update-version.sh
Labels: bug, non-breaking

#155 Update PyTorch to use CUDA 12.6
  ci/test_wheel_cugraph-pyg.sh
  conda/environments/all_cuda-126_arch-x86_64.yaml
  dependencies.yaml
Labels: breaking, improvement

#161 [FIX] Add mkl version, limit tensordict to 0.6.2
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
  python/cugraph-dgl/pyproject.toml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/pyproject.toml
Labels: bug, non-breaking

#160 Deprecate TensorDictFeatureStore in cuGraph-PyG
  python/cugraph-pyg/cugraph_pyg/data/__init__.py
Labels: improvement, non-breaking

#163 Branch 25.06 forward resolve
  .github/workflows/pr.yaml
  ci/test_wheel_cugraph-pyg.sh
  conda/environments/all_cuda-126_arch-x86_64.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
  python/cugraph-dgl/pyproject.toml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/cugraph_pyg/data/__init__.py
  python/cugraph-pyg/pyproject.toml
Labels: feature request, non-breaking

#166 Remove Dask API from cuGraph-PyG
  python/cugraph-pyg/cugraph_pyg/data/__init__.py
  python/cugraph-pyg/cugraph_pyg/data/dask_graph_store.py
  python/cugraph-pyg/cugraph_pyg/examples/graph_sage_mg.py
  python/cugraph-pyg/cugraph_pyg/examples/graph_sage_sg.py
  python/cugraph-pyg/cugraph_pyg/loader/__init__.py
  python/cugraph-pyg/cugraph_pyg/loader/dask_node_loader.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_dask_graph_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_dask_graph_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_dask_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_dask_neighbor_loader_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/sampler/test_sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tests/sampler/test_sampler_utils_mg.py
Labels: breaking, improvement
