Repository rapidsai/cugraph-gnn, pull requests merged in 2025-01, with the labels that each got.

#102 simplify wholegraph CMake, other small building and testing changes
  .pre-commit-config.yaml
  ci/build_cpp.sh
  ci/build_docs.sh
  ci/release/update-version.sh
  conda/recipes/pylibwholegraph/meta.yaml
  cpp/CMakeLists.txt
  cpp/Doxyfile
  python/pylibwholegraph/CMakeLists.txt
Labels: improvement, non-breaking

#103 remove flake8, clang tools from wholegraph CMake
  cpp/CMakeLists.txt
  cpp/cmake/CodeChecker.cmake
  python/pylibwholegraph/CMakeLists.txt
Labels: improvement, non-breaking

#105 Remove invalid conditional
  .github/workflows/test.yaml
Labels: bug, non-breaking

#106 Fix inputs for the workflow
  .github/workflows/test.yaml
Labels: bug, non-breaking

#100 Check if nightlies have succeeded recently enough
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#107 Remove Build Directory
  python/cugraph-pyg/build/lib/cugraph_pyg/VERSION
  python/cugraph-pyg/build/lib/cugraph_pyg/__init__.py
  python/cugraph-pyg/build/lib/cugraph_pyg/_version.py
  python/cugraph-pyg/build/lib/cugraph_pyg/data/__init__.py
  python/cugraph-pyg/build/lib/cugraph_pyg/data/cugraph_store.py
  python/cugraph-pyg/build/lib/cugraph_pyg/examples/graph_sage_mg.py
  python/cugraph-pyg/build/lib/cugraph_pyg/examples/graph_sage_sg.py
  python/cugraph-pyg/build/lib/cugraph_pyg/loader/__init__.py
  python/cugraph-pyg/build/lib/cugraph_pyg/loader/cugraph_node_loader.py
  python/cugraph-pyg/build/lib/cugraph_pyg/loader/filter.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/__init__.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/__init__.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/base.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/gat_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/gatv2_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/rgcn_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/sage_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/nn/conv/transformer_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/sampler/__init__.py
  python/cugraph-pyg/build/lib/cugraph_pyg/sampler/cugraph_sampler.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/conftest.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/mg/test_mg_cugraph_loader.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/mg/test_mg_cugraph_sampler.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/mg/test_mg_cugraph_store.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/nn/test_gat_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/nn/test_gatv2_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/nn/test_rgcn_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/nn/test_sage_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/nn/test_transformer_conv.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/test_cugraph_loader.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/test_cugraph_sampler.py
  python/cugraph-pyg/build/lib/cugraph_pyg/tests/test_cugraph_store.py
Labels: bug, non-breaking

#82 [FEA] Support Heterogeneous Sampling in cuGraph-PyG
  ci/test_notebooks.sh
  dependencies.yaml
  python/cugraph-dgl/cugraph_dgl/dataloading/neighbor_sampler.py
  python/cugraph-pyg/cugraph_pyg/data/graph_store.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
Labels: breaking, feature request

#109 wholegraph: remove debugging details from CMake
  cpp/CMakeLists.txt
  python/pylibwholegraph/CMakeLists.txt
Labels: improvement, non-breaking

#99 remove dependency on cugraph-ops
  ci/release/update-version.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-dgl/meta.yaml
  conda/recipes/cugraph-pyg/meta.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
  python/cugraph-dgl/cugraph_dgl/nn/conv/__init__.py
  python/cugraph-dgl/cugraph_dgl/nn/conv/base.py
  python/cugraph-dgl/cugraph_dgl/nn/conv/gatconv.py
  python/cugraph-dgl/cugraph_dgl/nn/conv/gatv2conv.py
  python/cugraph-dgl/cugraph_dgl/nn/conv/relgraphconv.py
  python/cugraph-dgl/cugraph_dgl/nn/conv/sageconv.py
  python/cugraph-dgl/cugraph_dgl/nn/conv/transformerconv.py
  python/cugraph-dgl/cugraph_dgl/tests/nn/test_gatconv.py
  python/cugraph-dgl/cugraph_dgl/tests/nn/test_gatv2conv.py
  python/cugraph-dgl/cugraph_dgl/tests/nn/test_relgraphconv.py
  python/cugraph-dgl/cugraph_dgl/tests/nn/test_sageconv.py
  python/cugraph-dgl/cugraph_dgl/tests/nn/test_transformerconv.py
  python/cugraph-dgl/pyproject.toml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/cugraph_pyg/__init__.py
  python/cugraph-pyg/cugraph_pyg/examples/graph_sage_mg.py
  python/cugraph-pyg/cugraph_pyg/examples/graph_sage_sg.py
  python/cugraph-pyg/cugraph_pyg/nn/__init__.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/__init__.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/base.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/gat_conv.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/gatv2_conv.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/hetero_gat_conv.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/rgcn_conv.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/sage_conv.py
  python/cugraph-pyg/cugraph_pyg/nn/conv/transformer_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_dask_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/tests/nn/test_gat_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/nn/test_gatv2_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/nn/test_hetero_gat_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/nn/test_rgcn_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/nn/test_sage_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/nn/test_transformer_conv.py
  python/cugraph-pyg/cugraph_pyg/tests/sampler/test_sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tests/sampler/test_sampler_utils_mg.py
  python/cugraph-pyg/pyproject.toml
  python/cugraph-pyg/pytest.ini
  python/pylibwholegraph/pylibwholegraph/torch/common_options.py
  python/pylibwholegraph/pylibwholegraph/torch/cugraphops/__init__.py
  python/pylibwholegraph/pylibwholegraph/torch/cugraphops/gat_conv.py
  python/pylibwholegraph/pylibwholegraph/torch/cugraphops/sage_conv.py
  python/pylibwholegraph/pylibwholegraph/torch/gnn_model.py
Labels: breaking, improvement

#108 Use GCC 13 in CUDA 12 conda builds.
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-pyg/conda_build_config.yaml
  conda/recipes/libwholegraph/conda_build_config.yaml
  conda/recipes/libwholegraph/meta.yaml
  conda/recipes/pylibwholegraph/conda_build_config.yaml
  conda/recipes/pylibwholegraph/meta.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#111 enforce `cmake-format` and `cmake-lint`, other small packaging changes
  .github/workflows/build.yaml
  .pre-commit-config.yaml
  ci/build_wheel.sh
  ci/build_wheel_pylibwholegraph.sh
  ci/check_style.sh
  ci/test_wheel_cugraph-dgl.sh
  ci/test_wheel_cugraph-pyg.sh
  ci/test_wheel_pylibwholegraph.sh
  cpp/CMakeLists.txt
  cpp/bench/CMakeLists.txt
  cpp/cmake/config.json
  cpp/cmake/thirdparty/get_nccl.cmake
  cpp/cmake/thirdparty/get_nvshmem.cmake
  cpp/cmake/thirdparty/get_raft.cmake
  cpp/scripts/run-cmake-format.sh
  cpp/tests/CMakeLists.txt
  python/pylibwholegraph/CMakeLists.txt
  python/pylibwholegraph/pylibwholegraph/binding/CMakeLists.txt
  rapids_config.cmake
Labels: improvement, non-breaking

#112 update pip devcontainers to UCX 1.18
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.5-pip/devcontainer.json
Labels: breaking, improvement

#114 Support PyG 2.6 in cuGraph-PyG
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-pyg/meta.yaml
  dependencies.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_snmg.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader_mg.py
  python/cugraph-pyg/pyproject.toml
Labels: improvement, non-breaking

#115 Build and test with CUDA 12.8.0
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/cuda12.8-pip/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  dependencies.yaml
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking

#121 Revert CUDA 12.8 shared workflow branch changes
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#122 Forward-merge branch-25.02 to branch-25.04
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/cuda12.8-pip/devcontainer.json
  .github/workflows/pr.yaml
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-pyg/meta.yaml
  dependencies.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_snmg.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader_mg.py
  python/cugraph-pyg/pyproject.toml
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking
