Repository rapidsai/cugraph-gnn, pull requests merged in 2025-05, with the labels that each got.

#193 fix(libwholegraph): set build_type to "nightly" and also publish wheel
  .github/workflows/build.yaml
Labels: improvement, non-breaking

#195 fix(libwholegraph): pass branch, sha, and date
  .github/workflows/build.yaml
Labels: improvement, non-breaking

#197 Add support for Python 3.13
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  dependencies.yaml
  python/cugraph-pyg/pyproject.toml
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking

#200 Build and test with CUDA 12.9.0
  .devcontainer/cuda12.9-conda/devcontainer.json
  .devcontainer/cuda12.9-pip/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-129_arch-aarch64.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-129_arch-x86_64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-129_arch-aarch64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-129_arch-x86_64.yaml
Labels: improvement, non-breaking

#199 Remove Dask API from cuGraph-DGL
  python/cugraph-dgl/cugraph_dgl/__init__.py
  python/cugraph-dgl/cugraph_dgl/convert.py
  python/cugraph-dgl/cugraph_dgl/cugraph_storage.py
  python/cugraph-dgl/cugraph_dgl/dataloading/__init__.py
  python/cugraph-dgl/cugraph_dgl/dataloading/dask_dataloader.py
  python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dask_dataloader.py
  python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dask_dataloader_mg.py
  python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dataset.py
  python/cugraph-dgl/cugraph_dgl/tests/test_cugraph_storage.py
  python/cugraph-dgl/cugraph_dgl/tests/test_from_dgl_heterograph.py
  python/cugraph-dgl/cugraph_dgl/tests/utils.py
  python/cugraph-dgl/examples/dataset_from_disk_cudf.ipynb
  python/cugraph-dgl/examples/graphsage/node-classification.py
  python/cugraph-dgl/examples/multi_trainer_MG_example/model.py
  python/cugraph-dgl/examples/multi_trainer_MG_example/workflow.py
Labels: breaking, improvement

#201 chore: skip DGL tests on Python 3.13
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/build_wheel.sh
  ci/test_wheel_cugraph-dgl.sh
  conda/recipes/libwholegraph/recipe.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#204 Quote head_rev in conda recipes
  conda/recipes/cugraph-dgl/recipe.yaml
  conda/recipes/cugraph-pyg/recipe.yaml
  conda/recipes/libwholegraph/recipe.yaml
  conda/recipes/pylibwholegraph/recipe.yaml
Labels: improvement, non-breaking

#203 use GitHub Actions artifacts
  ci/build_wheel_pylibwholegraph.sh
Labels: improvement, non-breaking

#202 Enable device code compression
  cpp/CMakeLists.txt
Labels: improvement, non-breaking

#205 Update to clang 20
  .pre-commit-config.yaml
  cpp/src/wholememory/communicator.cpp
  cpp/src/wholememory/file_io.cpp
  cpp/src/wholememory/memory_handle.cpp
Labels: improvement, non-breaking

#192 Reenable example tests
  ci/run_cugraph_pyg_pytests.sh
  ci/test.sh
  ci/test_python.sh
  ci/test_wheel_cugraph-pyg.sh
  datasets/get_test_data.sh
  dependencies.yaml
  python/cugraph-pyg/cugraph_pyg/examples/plc/pylibcugraph_mg.py
  python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
  python/cugraph-pyg/pyproject.toml
Labels: improvement, non-breaking

#207 [BUG] Remove FeatureStore tests about to break
  python/cugraph-pyg/cugraph_pyg/tests/conftest.py
Labels: bug, non-breaking

#208 Finish CUDA 12.9 migration and use branch-25.06 workflows
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/cuda12.8-pip/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-128_arch-aarch64.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-128_arch-x86_64.yaml
  python/cugraph-dgl/cugraph_dgl/utils/__init__.py
  python/cugraph-dgl/cugraph_dgl/utils/cugraph_conversion_utils.py
  python/cugraph-dgl/cugraph_dgl/utils/cugraph_storage_utils.py
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-128_arch-aarch64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-128_arch-x86_64.yaml
Labels: improvement, non-breaking

#209 [BUG] Fix DGL Test
  ci/test_notebooks.sh
  dependencies.yaml
  python/cugraph-dgl/cugraph_dgl/tests/test_graph_mg.py
Labels: bug, non-breaking

#212 use 'rapids-init-pip' in wheel CI, other CI changes
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/build_wheel_cugraph-dgl.sh
  ci/build_wheel_cugraph-pyg.sh
  ci/build_wheel_libwholegraph.sh
  ci/build_wheel_pylibwholegraph.sh
  ci/test_wheel_cugraph-dgl.sh
  ci/test_wheel_cugraph-pyg.sh
  ci/test_wheel_pylibwholegraph.sh
Labels: improvement, non-breaking

#216 use branch-25.08 of shared-workflows
  .github/workflows/build.yaml
Labels: improvement, non-breaking
