Repository rapidsai/cugraph-gnn, pull requests merged in 2025-07, with the labels that each got.

#235 add docs on CI workflow inputs
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: doc, non-breaking

#238 Improving the `taobao_mnmg` example.
  python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
Labels: improvement, non-breaking

#245 Propagate Changes from cuGraph Distributed Sampler (metadata addition)
  python/cugraph-pyg/cugraph_pyg/sampler/distributed_sampler.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tests/sampler/test_distributed_sampler.py
Labels: improvement, non-breaking

#246 fix(docker): use versioned `-latest` tag for all `rapidsai` images
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/release/update-version.sh
Labels: improvement, non-breaking

#236 [BUG] Specify Input Type and Assign Output to Correct Input Type
  python/cugraph-pyg/cugraph_pyg/sampler/sampler.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
Labels: bug, non-breaking, CRITICAL BUG

#228 Use GCC 14 in conda builds.
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/recipes/libwholegraph/conda_build_config.yaml
  conda/recipes/pylibwholegraph/conda_build_config.yaml
  cpp/tests/graph_ops/append_unique_test_utils.cu
  cpp/tests/graph_ops/append_unique_tests.cu
  cpp/tests/graph_ops/csr_add_self_loop_utils.cu
  dependencies.yaml
  python/libwholegraph/pyproject.toml
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking

#256 Disable codecov comments
  codecov.yml
Labels: improvement, non-breaking

#255 [BUG] Pin CPU Memory Instead of Copying to Device
  python/cugraph-pyg/cugraph_pyg/tensor/dist_tensor.py
Labels: bug, non-breaking, CRITICAL BUG

#258 [BUG] Correct De-Offset of Edge Label Index
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
Labels: bug, non-breaking, CRITICAL BUG

#264 remove cugraph-dgl CODEOWNERS rule, skip most CI on CODEOWNERS-only PRs
  .github/CODEOWNERS
  .github/workflows/pr.yaml
Labels: improvement, non-breaking
