Repository rapidsai/cugraph-gnn, pull requests merged in 2025-08, with the labels that each got.

#275 Reduce Seeds Per Call when running in CI Environment
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
Labels: bug, non-breaking

#273 Use rapids_cuda_enable_fatbin_compression
  cpp/CMakeLists.txt
Labels: improvement, non-breaking

#271 Remove cugraph Python library as a dependency
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/recipes/cugraph-pyg/recipe.yaml
  dependencies.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-129_arch-aarch64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-129_arch-x86_64.yaml
  python/cugraph-pyg/cugraph_pyg/data/feature_store.py
  python/cugraph-pyg/cugraph_pyg/data/graph_store.py
  python/cugraph-pyg/cugraph_pyg/examples/fraud/bitcoin_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/movielens_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/plc/pylibcugraph_mg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
  python/cugraph-pyg/cugraph_pyg/sampler/distributed_sampler.py
  python/cugraph-pyg/cugraph_pyg/sampler/io/reader.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tensor/dist_matrix.py
  python/cugraph-pyg/cugraph_pyg/tensor/dist_tensor.py
  python/cugraph-pyg/cugraph_pyg/tensor/utils.py
  python/cugraph-pyg/cugraph_pyg/tests/conftest.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/sampler/test_distributed_sampler.py
  python/cugraph-pyg/cugraph_pyg/tests/tensor/test_dist_tensor_mg.py
  python/cugraph-pyg/cugraph_pyg/utils/imports.py
  python/cugraph-pyg/pyproject.toml
Labels: improvement, non-breaking

#279 [CI] Disable Example Tests
  ci/run_cugraph_pyg_pytests.sh
  ci/test_wheel_cugraph-pyg.sh
Labels: bug, non-breaking

#272 Update rapids_config to handle user defined branch name
  cmake/RAPIDS.cmake
  cmake/rapids_config.cmake
Labels: breaking, improvement

#278 [BUG] Fix optional dependencies
  python/cugraph-pyg/cugraph_pyg/data/graph_store.py
  python/cugraph-pyg/cugraph_pyg/loader/utils.py
  python/cugraph-pyg/cugraph_pyg/sampler/distributed_sampler.py
  python/cugraph-pyg/cugraph_pyg/sampler/io/reader.py
Labels: bug, non-breaking

#274 Use build cluster in devcontainers
  .devcontainer/Dockerfile
  .devcontainer/cuda12.9-conda/devcontainer.json
  .devcontainer/cuda12.9-pip/devcontainer.json
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#284 libwholegraph wheels: use nvidia-nccl wheels instead of vendoring libnccl.so
  ci/build_wheel.sh
  ci/build_wheel_pylibwholegraph.sh
  ci/test_wheel_pylibwholegraph.sh
  cpp/CMakeLists.txt
  dependencies.yaml
  python/cugraph-pyg/pyproject.toml
  python/libwholegraph/CMakeLists.txt
  python/libwholegraph/pyproject.toml
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking
