Repository rapidsai/cugraph-gnn, pull requests merged in 2025-04, with the labels that each got.

#168 cugraph-pyg: remove Dask dependencies and related test code
  conda/recipes/cugraph-pyg/meta.yaml
  python/cugraph-pyg/cugraph_pyg/examples/start_dask.sh
  python/cugraph-pyg/cugraph_pyg/sampler/sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tests/conftest.py
  python/cugraph-pyg/pytest.ini
Labels: improvement, non-breaking

#175 restrict dgl dependency to x86
  conda/environments/all_cuda-118_arch-aarch64.yaml
  conda/environments/all_cuda-126_arch-aarch64.yaml
  conda/environments/all_cuda-126_arch-x86_64.yaml
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118_arch-aarch64.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118_arch-x86_64.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-128_arch-aarch64.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-128_arch-x86_64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118_arch-aarch64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118_arch-x86_64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-128_arch-aarch64.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-128_arch-x86_64.yaml
Labels: improvement, non-breaking

#177 Vendor RAPIDS.cmake
  cmake/RAPIDS.cmake
  cmake/rapids_config.cmake
  cpp/CMakeLists.txt
  python/pylibwholegraph/CMakeLists.txt
Labels: improvement, non-breaking

#172 [IMP] Make WholeGraph a Hard Dependency of cuGraph-PyG, Remove cuDF Spilling from Examples
  conda/recipes/cugraph-pyg/meta.yaml
  dependencies.yaml
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py
  python/cugraph-pyg/cugraph_pyg/examples/movielens_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_snmg.py
  python/cugraph-pyg/pyproject.toml
Labels: breaking, improvement

#171 [IMP] Remove SG and SNMG Examples
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py
  python/cugraph-pyg/cugraph_pyg/examples/pylibcugraph_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_sg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_snmg.py
Labels: breaking, improvement

#170 [HOTFIX] Add deprecation warnings for DGL classes
  .github/workflows/pr.yaml
  python/cugraph-dgl/cugraph_dgl/__init__.py
  python/cugraph-dgl/cugraph_dgl/convert.py
  python/cugraph-dgl/cugraph_dgl/dataloading/__init__.py
  python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dask_dataloader.py
  python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dask_dataloader_mg.py
Labels: bug, non-breaking

#181 Modify CMakeLists to install major version
  python/pylibwholegraph/CMakeLists.txt
Labels: breaking, bug

#156 [FEA] Support Unified WholeGraph FeatureStore and GraphStore
  python/cugraph-pyg/cugraph_pyg/data/__init__.py
  python/cugraph-pyg/cugraph_pyg/data/feature_store.py
  python/cugraph-pyg/cugraph_pyg/data/graph_store.py
  python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
  python/cugraph-pyg/cugraph_pyg/tensor/__init__.py
  python/cugraph-pyg/cugraph_pyg/tensor/dist_matrix.py
  python/cugraph-pyg/cugraph_pyg/tensor/dist_tensor.py
  python/cugraph-pyg/cugraph_pyg/tensor/utils.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_feature_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/data/test_graph_store_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/tensor/test_dist_matrix_mg.py
  python/cugraph-pyg/cugraph_pyg/tests/tensor/test_dist_tensor_mg.py
Labels: breaking, improvement

#189 added downloads from github
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  ci/build_docs.sh
  ci/build_python.sh
  ci/test_cpp.sh
  ci/test_notebooks.sh
  ci/test_python.sh
  ci/test_wheel_cugraph-dgl.sh
  ci/test_wheel_cugraph-pyg.sh
  ci/test_wheel_pylibwholegraph.sh
Labels: improvement, non-breaking

#191 [DOC] Add warning of pending DGL removal
  README.md
Labels: doc, non-breaking

#190 [DOC] Update the README to show the current stack
  README.md
  img/Stack.png
  img/Stack2.png
  img/cugraph-pyg-stack.png
Labels: doc, non-breaking
