Repository rapidsai/cugraph-gnn, pull requests merged in 2025-09, with the labels that each got.

#295 build with RAPIDS CUDA architectures
  .pre-commit-config.yaml
  build.sh
Labels: breaking, improvement

#301 [BUG] Fix input type in Taobao example
  python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
Labels: bug, non-breaking

#308 Configure repo for automatic release notes generation
  .github/release.yml
Labels: improvement, non-breaking

#312 fix condition to skip CUDA 13 conda-python-tests jobs
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#310 [FEA] Enable Temporal Sampling in cuGraph-PyG
  python/cugraph-pyg/cugraph_pyg/data/graph_store.py
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
  python/cugraph-pyg/cugraph_pyg/sampler/distributed_sampler.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
Labels: feature request, non-breaking
