Repository rapidsai/cugraph-gnn, pull requests merged in 2025-02, with the labels that each got.

#104 Heterogeneous Link Prediction Example for cuGraph-PyG
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
  python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
  python/cugraph-pyg/cugraph_pyg/data/graph_store.py
  python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
  python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler.py
  python/cugraph-pyg/cugraph_pyg/sampler/sampler_utils.py
  python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader_mg.py
Labels: improvement, non-breaking

#123 disallow fallback to Make in Python builds
  dependencies.yaml
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking

#118 Deprecate the Dask API in cuGraph-PyG
  python/cugraph-pyg/cugraph_pyg/data/__init__.py
  python/cugraph-pyg/cugraph_pyg/examples/graph_sage_mg.py
  python/cugraph-pyg/cugraph_pyg/examples/graph_sage_sg.py
  python/cugraph-pyg/cugraph_pyg/loader/__init__.py
Labels: improvement, non-breaking

#128 Fix of create_node_classification_datasets
  python/pylibwholegraph/examples/node_classfication.py
  python/pylibwholegraph/pylibwholegraph/torch/__init__.py
  python/pylibwholegraph/pylibwholegraph/torch/data_loader.py
Labels: feature request, non-breaking

#132 Update CuPy Version to 13.2
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-dgl/meta.yaml
  conda/recipes/cugraph-pyg/meta.yaml
  dependencies.yaml
Labels: breaking, bug

#133 Use `rapids-pip-retry` in CI jobs that might need retries
  ci/build_wheel.sh
  ci/test_wheel_cugraph-dgl.sh
  ci/test_wheel_cugraph-pyg.sh
  ci/test_wheel_pylibwholegraph.sh
Labels: improvement, non-breaking

#119 Migrate to NVKS for amd64 CI runners
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  ci/run_cugraph_pyg_pytests.sh
  ci/test_wheel_cugraph-pyg.sh
Labels: improvement, non-breaking

#50 [FEA] Support Link Prediction and Negative Sampling in cuGraph-DGL
  python/cugraph-dgl/cugraph_dgl/graph.py
  python/cugraph-dgl/cugraph_dgl/tests/conftest.py
  python/cugraph-dgl/cugraph_dgl/tests/test_graph.py
  python/cugraph-dgl/cugraph_dgl/tests/test_graph_mg.py
Labels: breaking, feature request

#136 [BUG] Fix bug with drop_last when mod is 0
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
  python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
Labels: bug, non-breaking

#148 Update DGL Packages to PyTorch 2.4
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-dgl/meta.yaml
  dependencies.yaml
  python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
Labels: breaking, bug

#141 [FEA] New MovieLens Example, Add Timing to Taobao Example
  python/cugraph-pyg/cugraph_pyg/examples/movielens_mnmg.py
  python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
  python/cugraph-pyg/cugraph_pyg/loader/link_loader.py
Labels: feature request, non-breaking

#138 Use shared-workflows branch-25.04
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#147 Require CMake 3.30.4
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/all_cuda-124_arch-x86_64.yaml
  conda/recipes/cugraph-pyg/conda_build_config.yaml
  conda/recipes/libwholegraph/conda_build_config.yaml
  conda/recipes/pylibwholegraph/conda_build_config.yaml
  cpp/CMakeLists.txt
  dependencies.yaml
  python/pylibwholegraph/CMakeLists.txt
  python/pylibwholegraph/pyproject.toml
Labels: improvement, non-breaking

#144 Create Conda CI test env in one step
  ci/build_docs.sh
  ci/release/update-version.sh
  ci/test_cpp.sh
  ci/test_python.sh
  dependencies.yaml
Labels: improvement, non-breaking

#149 add cugraph-notebook-codeowners to CODEOWNERS
  .github/CODEOWNERS
Labels: improvement, non-breaking

#150 Use conda-build instead of conda-mambabuild
  ci/build_cpp.sh
  ci/build_python.sh
  ci/test_notebooks.sh
  ci/test_python.sh
  python/cugraph-dgl/README.md
Labels: improvement, non-breaking
